language: python
python:
  - "2.7"
  - "3.2"
before_install:
  - "sudo apt-get install -qq python-lxml"
install: 
  - "bundle install"
before_script: "rake dump" #output vim version
script:
  - "nosetests python" #run the python tests
  - "rake test" #run the vspec tests
